api = "0.2"

[buildpack]
id = "heroku/nodejs-engine"
name = "Node Buildpack"
version = "0.7.0"

[[stacks]]
id = "heroku-18"

[[stacks]]
id = "heroku-20"

[[stacks]]
id = "io.buildpacks.stacks.bionic"
